# the directory where all raw and temporary datasets will be downloaded and processed
data-dir: /external/aedes-americas/data-raw/

# set where the maxent input files will go
data-mx-in: /external/aedes-americas/data-mx-in/
data-mx-out: /external/aedes-americas/data-mx-out/

# the output map projection
epsg: 54009

# the output grid sizes for multi-scale analysis (in meters)
grid-size: [1000, 5000, 10000, 50000, 100000]

# the output map extent in [xmin, ymin, xmax, ymax] per the output map projection
bounds: [-11864000, -6477000, -2010000, 3962000]

# consistent nodata value
nodata: -9999

# set the band naming conventions
prefix:
    leaf_area: lai
    livestock: cow
    population: pop
    precipitation: pcp
    temperature: lst
    tree_cover: tc